const $ = id => document.getElementById(id);
const screens = [...document.querySelectorAll('.screen')];
const canvas = $('game'), ctx = canvas.getContext('2d');
const terrain = new Image(); terrain.src = 'assets/north-kivu-terrain.webp';
function storeGet(key){try{return localStorage.getItem(key);}catch{return null;}}
function storeSet(key,value){try{localStorage.setItem(key,value);return true;}catch{return false;}}

const audio={ctx:null,music:.55,gun:.7,fx:.8,tick:0,timer:null,musicVoices:new Set()};
function initAudio(){if(audio.ctx)return;audio.ctx=new (window.AudioContext||window.webkitAudioContext)();}
function tone(freq,duration=.12,volume=.12,type='sine',delay=0,channel='fx'){if(!audio.ctx)return;const t=audio.ctx.currentTime+delay,o=audio.ctx.createOscillator(),g=audio.ctx.createGain(),level=audio[channel]??audio.fx;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(Math.max(.0001,volume*level),t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(audio.ctx.destination);if(channel==='music'){audio.musicVoices.add(o);o.onended=()=>audio.musicVoices.delete(o);}o.start(t);o.stop(t+duration);}
function noise(volume=.12,duration=.08,channel='gun'){if(!audio.ctx)return;const len=audio.ctx.sampleRate*duration,b=audio.ctx.createBuffer(1,len,audio.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*(1-i/len);const s=audio.ctx.createBufferSource(),g=audio.ctx.createGain();s.buffer=b;g.gain.value=volume*(audio[channel]??audio.fx);s.connect(g).connect(audio.ctx.destination);s.start();}
function sfx(name){if(name==='gun'){noise(.13,.07);tone(92,.08,.08,'square',0,'gun');}if(name==='hit'){tone(105,.16,.11,'sawtooth');}if(name==='save'){tone(523,.12,.1);tone(659,.13,.09,'sine',.1);tone(784,.18,.08,'sine',.2);}if(name==='loss'){tone(220,.2,.12,'sawtooth');tone(147,.35,.11,'sawtooth',.14);}if(name==='warning'){tone(330,.1,.1,'square');tone(330,.1,.1,'square',.18);}if(name==='danger'){tone(880,.08,.09,'square');tone(660,.08,.08,'square',.11);}if(name==='gameover'){tone(196,.3,.15,'sawtooth');tone(147,.45,.14,'triangle',.22);tone(98,.8,.13,'sawtooth',.5);}if(name==='victory'){[392,494,587,784].forEach((n,i)=>tone(n,.28,.1,'triangle',i*.11));}}
function dangerLevel(){if(!S.running)return 0;const alive=S.squad.filter(s=>s.hp>0).length,near=S.enemies.filter(e=>e.hp>0&&dist(e,S.player)<290).length;return Math.min(3,(S.bullets.length>2?1:0)+(near>1?1:0)+(alive<=2?1:0)+(alive===0?1:0));}
function liveGameplay(){return !!(S.running&&!S.paused&&$('game-screen').classList.contains('active')&&$('dialogue').classList.contains('hidden')&&$('game-over').classList.contains('hidden')&&!$('settings-dialog').open&&$('pause-overlay').classList.contains('hidden'));}
function stopMusic(){clearTimeout(audio.timer);audio.timer=null;for(const o of audio.musicVoices){try{o.stop();}catch{}}audio.musicVoices.clear();}
function silenceAll(){stopMusic();audio.ctx?.suspend();}
function activateAudio(){if(!audio.ctx||!liveGameplay())return;audio.ctx.resume().then(musicLoop).catch(()=>{});}
function musicLoop(){stopMusic();if(!liveGameplay()||!audio.ctx||audio.music<=0)return;const danger=dangerLevel(),scale=[110,147,165,196,220,165,147,123],n=scale[audio.tick%scale.length];tone(n,.34,.07+danger*.012,'triangle',0,'music');tone(55+(audio.tick%2)*10,.16,.055+danger*.018,'sine',0,'music');if(audio.tick%2===1)tone(n*2,.09,.032+danger*.008,'sine',.04,'music');if(danger>=1)noise(.018+danger*.009,.035,'music');if(danger>=2&&audio.tick%2===0)tone(330,.055,.035,'square',.08,'music');audio.tick++;audio.timer=setTimeout(musicLoop,Math.max(215,410-danger*58));}

const S = {running:false,paused:false,mission:0,health:100,score:0,teamDamage:0,time:0,last:0,lang:storeGet('m23-language')||'en',keys:new Set(),
  player:{x:80,y:270,r:15,speed:175,faceX:1,faceY:0},touchX:0,touchY:0,touchPointer:null,targets:[],enemies:[],squad:[],bullets:[],particles:[],completed:0,cooldown:0,ambush:false,zoneWarn:0};

const missions=[
 {place:'GOMA • NYIRAGONGO',title:'Escort 5 families from the lava road',intro:['Captain Mamadou Ndala','Stay together. Our first duty is to protect the population.'],start:[75,270],
  targets:[[290,105,'civilian'],[420,410,'civilian'],[590,150,'civilian'],[730,340,'civilian'],[865,115,'civilian']],enemies:[[250,330,85],[425,165,95],[575,390,105],[720,120,90],[845,330,80]],squad:5,zones:[[640,0,34,540,3,'LAVA SECURITY LINE']]},
 {place:'RUTSHURU • RN2 CORRIDOR',title:'Secure 5 medicine crates and 1 family',intro:['Radio','M23 positions are ahead. The clinic convoy cannot pass until the road is secure.'],start:[80,445],
  targets:[[245,105,'supplies'],[360,410,'supplies'],[520,155,'supplies'],[675,385,'supplies'],[845,125,'supplies'],[850,410,'civilian']],enemies:[[235,350,110],[380,185,115],[520,400,120],[650,145,80],[760,345,100],[870,260,80]],squad:6,zones:[[605,0,38,540,3,'CONTESTED CHECKPOINT']]},
 {place:'NGADI • NORTH OF BENI',title:'Travel with the convoy to Ngadi',intro:['Radio • 2 January 2014','Colonel, the road north of Beni is exposed. Keep the convoy close.'],start:[90,270],
  targets:[[520,270,'checkpoint'],[835,270,'checkpoint']],enemies:[[350,145,95],[475,390,110],[620,140,80],[745,390,75]],squad:6,zones:[[585,0,42,540,1,'MILITARY ROADBLOCK']],final:true}
];

const frMissions=[
 {title:'Escorter 5 familles hors de la route de lave',intro:['Capitaine Mamadou Ndala','Restez groupés. Notre premier devoir est de protéger la population.']},
 {title:'Sécuriser 5 caisses médicales et 1 famille',intro:['Radio','Des positions M23 sont devant nous. Le convoi médical ne peut pas passer avant la sécurisation de la route.']},
 {title:'Accompagner le convoi jusqu’à Ngadi',intro:['Radio • 2 janvier 2014','Colonel, la route au nord de Beni est exposée. Gardez le convoi près de vous.']}
];
const words={
 en:{begin:'Begin mission',continueSave:'Continue saved campaign',how:'How to play',howBody:'Phone: touch and drag anywhere on the left side to move and aim. Tap the right side or OK to fire or interact. The joystick appears under your thumb.',desktop:'Desktop: arrows or WASD to move, Enter or Space for OK, P or Escape to pause.',back:'Back',language:'Language',eyebrow:'A STORY FROM EASTERN CONGO',subtitle:'A short 2D prototype inspired by the courage of Colonel Mamadou Ndala and the civilians caught in war.',history:'Historical note',historyNote:'This is a fictionalized educational drama, not a documentary. Dialogue and missions are invented. Violence is stylized and non-graphic.',resume:'Resume',save:'Save campaign',quit:'Save and quit to menu',paused:'Operation suspended',saveReady:'Your position can be saved on this device.',saved:'Campaign saved on this device.',retry:'Retry mission',restart:'Restart campaign',failed:'Mamadou has fallen',score:'Score',map:'MAP',continue:'Continue',playAgain:'Play again',endingTitle:'A soldier falls. A story remains.',endingBody:'On 2 January 2014, Mamadou Ndala and two soldiers were killed when their convoy was attacked near Ngadi, north of Beni. A United Nations report described the assailants as unidentified. This game does not claim to resolve the disputed responsibility.',dedication:'Dedicated to civilians and peacekeepers who have lost their lives in eastern Congo.'},
 fr:{begin:'Commencer la mission',continueSave:'Continuer la campagne sauvegardée',how:'Comment jouer',howBody:'Téléphone : touchez et glissez n’importe où à gauche pour bouger et viser. Touchez la droite ou OK pour tirer ou interagir. Le joystick apparaît sous votre pouce.',desktop:'Ordinateur : flèches ou WASD pour bouger, Entrée ou Espace pour OK, P ou Échap pour pause.',back:'Retour',language:'Langue',eyebrow:'UNE HISTOIRE DE L’EST DU CONGO',subtitle:'Un court jeu 2D inspiré par le courage du colonel Mamadou Ndala et des civils pris dans la guerre.',history:'Note historique',historyNote:'Ceci est un drame éducatif romancé, pas un documentaire. Les dialogues et missions sont inventés. La violence est stylisée et non graphique.',resume:'Reprendre',save:'Sauvegarder la campagne',quit:'Sauvegarder et quitter au menu',paused:'Opération suspendue',saveReady:'Votre position peut être sauvegardée sur cet appareil.',saved:'Campagne sauvegardée sur cet appareil.',retry:'Recommencer la mission',restart:'Recommencer la campagne',failed:'Mamadou est tombé',score:'Score',map:'CARTE',continue:'Continuer',playAgain:'Rejouer',endingTitle:'Un soldat tombe. Une histoire demeure.',endingBody:'Le 2 janvier 2014, Mamadou Ndala et deux soldats ont été tués lorsque leur convoi a été attaqué près de Ngadi, au nord de Beni. Un rapport des Nations Unies a décrit les assaillants comme non identifiés. Ce jeu ne prétend pas résoudre cette responsabilité contestée.',dedication:'Dédié aux civils et aux soldats de la paix qui ont perdu la vie dans l’est du Congo.'}
};
const aboutWords={en:{button:'Credits & Support',title:'Credits & Support',creator:'Created by',privacy:'Privacy',note:'This game stores settings and campaign saves only on your device. Feedback is sent only when you choose email. It uses no accounts, advertising, tracking, or analytics.',version:'Prototype version 0.3.0'},fr:{button:'Crédits et assistance',title:'Crédits et assistance',creator:'Créé par',privacy:'Confidentialité',note:'Ce jeu stocke les réglages et les sauvegardes uniquement sur votre appareil. Un avis est envoyé seulement lorsque vous choisissez l’e-mail. Il n’utilise aucun compte, publicité, suivi ou outil d’analyse.',version:'Version prototype 0.3.0'}};
const feedbackWords={
 en:{button:'Send feedback',eyebrow:'HELP IMPROVE THE GAME',title:'Player feedback',intro:'Your report goes directly to the creator. No information is sent until you choose Email report.',rating:'Overall experience',type:'What would you like to report?',types:['General feedback','Controls or gameplay','Bug or performance problem','Story or historical accuracy','Sound or music'],message:'Tell us what happened or what should improve',placeholder:'Please include the mission and what you expected to happen.',diagnostics:'Include basic device and game information to help diagnose problems',privacy:'The diagnostic report includes browser type, screen size, language and saved mission—not your name, location or phone number.',email:'Email report',copy:'Copy report',ending:'Share your feedback',copied:'Report copied. You can paste it into an email or message.',copyFailed:'Could not copy automatically. Select and copy your message.',subject:'M23: The Last Patrol — Player feedback'},
 fr:{button:'Donner mon avis',eyebrow:'AIDEZ-NOUS À AMÉLIORER LE JEU',title:'Avis du joueur',intro:'Votre rapport est envoyé directement au créateur. Aucune information n’est transmise avant que vous choisissiez Envoyer par e-mail.',rating:'Expérience globale',type:'Que souhaitez-vous signaler ?',types:['Avis général','Commandes ou jouabilité','Bug ou problème de performance','Histoire ou exactitude historique','Son ou musique'],message:'Expliquez ce qui s’est passé ou ce qui devrait être amélioré',placeholder:'Indiquez la mission et ce qui aurait dû se passer.',diagnostics:'Inclure les informations de base sur l’appareil et le jeu pour aider au diagnostic',privacy:'Le rapport technique comprend le navigateur, la taille d’écran, la langue et la mission sauvegardée — pas votre nom, votre position ni votre numéro.',email:'Envoyer par e-mail',copy:'Copier le rapport',ending:'Donner votre avis',copied:'Rapport copié. Vous pouvez le coller dans un e-mail ou un message.',copyFailed:'Copie automatique impossible. Sélectionnez et copiez votre message.',subject:'M23 : The Last Patrol — Avis du joueur'}
};
function L(key){return words[S.lang||'en'][key]||words.en[key]||key;}
function localizedMission(i=S.mission){return S.lang==='fr'?{...missions[i],...frMissions[i]}:missions[i];}
function applyLanguage(){document.documentElement.lang=S.lang;$('language-select').value=S.lang;$('start-eyebrow').textContent=L('eyebrow');$('start-subtitle').textContent=L('subtitle');$('history-label').textContent=L('history');$('history-note').textContent=L('historyNote');$('language-label').textContent=L('language');$('start-btn').textContent=L('begin');$('continue-save-btn').textContent=L('continueSave');$('how-btn').textContent=L('how');$('how-title').textContent=L('how');$('how-body').textContent=L('howBody');$('how-desktop').textContent=L('desktop');$('back-btn').textContent=L('back');$('pause-title').textContent=L('paused');$('save-status').textContent=L('saveReady');$('resume-btn').textContent=L('resume');$('save-btn').textContent=L('save');$('quit-btn').textContent=L('quit');$('retry-btn').textContent=L('retry');$('campaign-btn').textContent=L('restart');$('game-over-title').textContent=L('failed');$('map-btn').textContent=L('map');$('map-continue-btn').textContent=L('continue');$('continue-btn').textContent=L('continue');$('ending-title').textContent=L('endingTitle');$('ending-body').textContent=L('endingBody');$('ending-dedication').textContent=L('dedication');$('restart-btn').textContent=L('playAgain');const aw=aboutWords[S.lang];$('about-btn').textContent=aw.button;$('about-title').textContent=aw.title;$('creator-label').textContent=aw.creator;$('privacy-title').textContent=aw.privacy;$('privacy-note').textContent=aw.note;$('version-label').textContent=aw.version;$('about-back-btn').textContent=L('back');const labels=S.lang==='fr'?['MISSION','OBJECTIF','ÉQUIPE','MAMADOU','SCORE']:['MISSION','OBJECTIVE','TEAM','MAMADOU','SCORE'];document.querySelectorAll('.hud .label').forEach((el,i)=>el.textContent=labels[i]);}
function applyFeedbackLanguage(){const f=feedbackWords[S.lang];$('feedback-btn').textContent=f.button;$('feedback-eyebrow').textContent=f.eyebrow;$('feedback-title').textContent=f.title;$('feedback-intro').textContent=f.intro;$('rating-label').textContent=f.rating;document.querySelector('.rating').setAttribute('aria-label',f.rating);document.querySelectorAll('.rating label').forEach((label,i)=>label.setAttribute('aria-label',S.lang==='fr'?`${i+1} sur 5`:`${i+1} out of 5`));$('feedback-type-label').textContent=f.type;['general','controls','bug','story','audio'].forEach((id,i)=>{const o=$('type-'+id);o.textContent=f.types[i];o.value=f.types[i];});$('feedback-message-label').textContent=f.message;$('feedback-message').placeholder=f.placeholder;$('diagnostics-label').textContent=f.diagnostics;$('feedback-privacy').textContent=f.privacy;$('email-feedback-btn').textContent=f.email;$('copy-feedback-btn').textContent=f.copy;$('feedback-back-btn').textContent=L('back');$('ending-feedback-btn').textContent=f.ending;}
function updateSaveButton(){$('continue-save-btn').classList.toggle('hidden',!storeGet('m23-save-v2'));}
function saveGame(silent=false){if(!S.running||S.ambush)return false;const data={version:2,lang:S.lang,mission:S.mission,health:S.health,score:S.score,teamDamage:S.teamDamage,completed:S.completed,player:{x:S.player.x,y:S.player.y,faceX:S.player.faceX,faceY:S.player.faceY},targets:S.targets.map(t=>({done:t.done})),squad:S.squad.map(s=>({x:s.x,y:s.y,hp:s.hp})),enemies:S.enemies.map(e=>({x:e.x,hp:e.hp,dir:e.dir})),savedAt:Date.now()},saved=storeSet('m23-save-v2',JSON.stringify(data));updateSaveButton();if(!silent){$('save-status').textContent=saved?L('saved'):(S.lang==='fr'?'Sauvegarde indisponible sur cet appareil.':'Saving is unavailable on this device.');if(saved)sfx('save');}return saved;}
function loadSavedGame(){requestGameFullscreen();let d;try{d=JSON.parse(storeGet('m23-save-v2'));}catch{return;}if(!d||d.version!==2)return;S.lang=d.lang||S.lang;applyLanguage();S.running=true;S.paused=false;S.mission=Math.max(0,Math.min(missions.length-1,d.mission||0));S.health=d.health??100;S.score=d.score??0;S.last=performance.now();initAudio();show('game-screen');loadMission();S.health=d.health??100;S.score=d.score??0;S.teamDamage=d.teamDamage??0;S.completed=d.completed??0;Object.assign(S.player,d.player||{});S.targets.forEach((t,i)=>t.done=!!d.targets?.[i]?.done);S.squad.forEach((s,i)=>Object.assign(s,d.squad?.[i]||{}));S.enemies.forEach((e,i)=>Object.assign(e,d.enemies?.[i]||{}));$('dialogue').classList.add('hidden');S.paused=false;$('objective-label').textContent=`${localizedMission().title} • ${S.completed}/${S.targets.length}`;updateHud();activateAudio();requestAnimationFrame(loop);if(S.completed===S.targets.length)setTimeout(finishObjective,700);}
function stopAudio(){stopMusic();window.speechSynthesis?.cancel();if(audio.ctx){audio.ctx.close();audio.ctx=null;}}
function resetTouch(){S.touchX=0;S.touchY=0;S.touchPointer=null;$('virtual-stick').classList.add('hidden');$('stick-knob').style.transform='translate(0,0)';}
function pauseGame(){if(!S.running||S.paused)return;S.paused=true;resetTouch();silenceAll();$('save-status').textContent=L('saveReady');$('pause-overlay').classList.remove('hidden');saveGame(true);}
function resumeGame(){$('pause-overlay').classList.add('hidden');S.paused=false;S.last=performance.now();activateAudio();}
function quitToMenu(){saveGame(true);S.running=false;S.paused=false;S.keys.clear();$('pause-overlay').classList.add('hidden');stopAudio();show('start-screen');updateSaveButton();}

function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));document.body.classList.toggle('in-game',id==='game-screen');if(id!=='game-screen')resetTouch();}
function openMap(next=false){S.paused=true;silenceAll();show('map-screen');document.querySelectorAll('.place').forEach(p=>p.classList.toggle('current',+p.dataset.stage===S.mission));
 $('map-note').textContent=missions[S.mission]?.place+' — '+localizedMission().title;
 $('map-continue-btn').onclick=()=>{show('game-screen');S.paused=false;if(next)loadMission();else activateAudio();};}
function requestGameFullscreen(){const el=document.documentElement,request=el.requestFullscreen||el.webkitRequestFullscreen;if(request&&!document.fullscreenElement){try{const result=request.call(el,{navigationUI:'hide'});result?.then(()=>screen.orientation?.lock?.('landscape').catch(()=>{})).catch(()=>{});}catch{}}}
function begin(){requestGameFullscreen();S.running=true;S.mission=0;S.health=100;S.score=0;S.last=performance.now();initAudio();openMap(true);requestAnimationFrame(loop);}

function loadMission(){const m=missions[S.mission],lm=localizedMission();S.player.x=m.start[0];S.player.y=m.start[1];S.health=Math.min(100,S.health+25);S.teamDamage=0;S.completed=0;S.ambush=false;
 $('game-over').classList.add('hidden');
 S.targets=m.targets.map(([x,y,type])=>({x,y,type,done:false}));
 S.enemies=m.enemies.map(([x,y,range],i)=>({x,y,home:x,range,dir:i%2?1:-1,speed:32+i*4+S.mission*5,hp:2+S.mission,shot:.9+Math.random()*1.3-S.mission*.12}));
 S.squad=Array.from({length:m.squad},(_,i)=>({x:S.player.x-28-(i%2)*25,y:S.player.y+(i-Math.floor(m.squad/2))*24,hp:2}));S.bullets=[];
 $('mission-label').textContent=`${S.mission+1} / ${missions.length}`;$('mission-label').title=m.place;$('objective-label').textContent=`${lm.title} • 0/${S.targets.length}`;$('morale-label').textContent=Math.round(S.health);updateHud();say(...lm.intro);setTimeout(()=>saveGame(true),0);}
function say(speaker,line,done){S.paused=true;silenceAll();$('speaker').textContent=speaker;$('line').textContent=line;$('dialogue').classList.remove('hidden');$('continue-btn').onclick=()=>{$('dialogue').classList.add('hidden');S.paused=false;done?.();activateAudio();};}
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.add('hidden'),1300);}
function feedback(text,type=''){const el=document.createElement('div');el.className=`float-score ${type}`;el.textContent=text;el.style.left=`${42+Math.random()*16}%`;el.style.top=`${38+Math.random()*16}%`;$('feedback-layer').append(el);setTimeout(()=>el.remove(),1250);}
function updateHud(){const alive=S.squad.filter(s=>s.hp>0).length,protection=Math.max(0,Math.round((42-S.teamDamage)/42*100));$('team-label').textContent=`${alive} • ${protection}%`;$('team-label').title='Soldiers remaining • protection before next casualty';$('score-label').textContent=S.score;$('morale-label').textContent=Math.round(S.health);}

function performAction(){if(!S.running||S.paused||S.cooldown>0)return;S.cooldown=.32;
 const t=S.targets.find(t=>!t.done&&dist(t,S.player)<65);if(t){t.done=true;S.completed++;const gain=t.type==='civilian'?250:t.type==='supplies'?180:300;S.score+=gain;const msg=S.lang==='fr'?{civilian:'Famille escortée en sécurité',supplies:'Médicaments sécurisés',checkpoint:'Point de contrôle sécurisé'}:{civilian:'Family escorted to safety',supplies:'Medicine secured',checkpoint:'Convoy checkpoint secured'};toast(msg[t.type]);feedback(`+${gain}`,'save');sfx('save');burst(t.x,t.y,'#e0b45a');$('objective-label').textContent=`${localizedMission().title} • ${S.completed}/${S.targets.length}`;updateHud();saveGame(true);if(S.completed===S.targets.length)setTimeout(finishObjective,650);return;}
 const aim={x:S.player.x+S.player.faceX*340,y:S.player.y+S.player.faceY*340};fire(S.player,aim,'friendly');}
function finishObjective(){const m=missions[S.mission];if(m.final){startAmbush();return;}S.score+=500;sfx('victory');feedback('+500 MISSION','save');const text=S.lang==='fr'?['Mission sécurisée',`Le secteur de ${m.place.split(' • ')[0]} est ouvert. La colonne continue vers le nord.`]:['Mission secured',`The ${m.place.split(' • ')[0]} sector is open. The column continues north.`];say(...text,()=>{S.mission++;openMap(true);});}
function startAmbush(){S.ambush=true;S.paused=true;sfx('warning');const a=S.lang==='fr'?['Soldat','Colonel — mouvement dans les arbres ! La route est bloquée derrière nous !','PIÈGE • LE CONVOI EST ENCERCLÉ']:['Squad soldier','Colonel—movement in the trees! The road is blocked behind us!','TRAP • THE CONVOY IS SURROUNDED'];say(a[0],a[1],()=>{S.paused=false;toast(a[2]);setTimeout(scriptedStrike,3200);});}
function scriptedStrike(){if(!S.running)return;S.paused=true;sfx('warning');const sx=950,sy=130;S.bullets.push({x:sx,y:sy,vx:(S.player.x-sx)/1.1,vy:(S.player.y-sy)/1.1,side:'rocket',life:1.1});setTimeout(()=>{noise(.4,.35);burst(S.player.x,S.player.y,'#e28652',55);S.health=0;S.squad.slice(0,2).forEach(s=>s.hp=0);updateHud();setTimeout(()=>{const h=S.lang==='fr'?['Événement historique','Mamadou Ndala et deux soldats ont été tués dans l’embuscade près de Ngadi.']:['Historical event','Mamadou Ndala and two soldiers were killed in the ambush near Ngadi.'];say(...h,()=>{S.running=false;stopAudio();show('ending-screen');});},800);},1100);}

function fire(from,to,side){const d=Math.hypot(to.x-from.x,to.y-from.y)||1;S.bullets.push({x:from.x,y:from.y,vx:(to.x-from.x)/d*300,vy:(to.y-from.y)/d*300,side,life:2});sfx('gun');}
function burst(x,y,color,n=18){for(let i=0;i<n;i++)S.particles.push({x,y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:.5+Math.random(),color});}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
function damagePlayer(n){if(S.ambush||S.paused)return;const alive=S.squad.filter(s=>s.hp>0);sfx('hit');if(alive.length){S.teamDamage+=n;S.health=Math.max(40,S.health-n*.12);feedback('TEAM HIT','loss');if(S.teamDamage>=42){const lost=alive[alive.length-1];lost.hp=0;S.teamDamage=0;S.score=Math.max(0,S.score-200);sfx('loss');feedback('-1 SOLDIER','loss');toast(S.squad.some(s=>s.hp>0)?'A soldier has fallen • protect the remaining team':'SQUAD LOST • MAMADOU IS EXPOSED');if(!S.squad.some(s=>s.hp>0))sfx('danger');}}else{S.health=Math.max(0,S.health-n*.55);feedback(`-${Math.round(n*.55)} HEALTH`,'loss');if(S.health<=35&&S.health>0)sfx('danger');}
 updateHud();if(S.health<=0)showGameOver();}
function failureMessage(){const en=['Goma has fallen. The evacuation route is lost.','Rutshuru has been lost. The medical corridor is cut.','The Beni convoy has been destroyed before reaching Ngadi.'],fr=['Goma est tombée. La route d’évacuation est perdue.','Rutshuru est perdue. Le corridor médical est coupé.','Le convoi de Beni a été détruit avant d’atteindre Ngadi.'];return(S.lang==='fr'?fr:en)[S.mission];}
function speakRadio(text){if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=S.lang==='fr'?'fr-FR':'en-US';u.rate=.92;u.pitch=.78;u.volume=audio.fx;window.speechSynthesis.speak(u);}
function showGameOver(){S.paused=true;stopMusic();S.keys.clear();S.score=Math.max(0,S.score-300);updateHud();sfx('gameover');const consequence=failureMessage();$('game-over-title').textContent=L('failed');$('failure-consequence').textContent=consequence;$('failed-score').textContent=`${L('score')}: ${S.score}`;$('game-over').classList.remove('hidden');speakRadio(consequence);}
function retryMission(){window.speechSynthesis?.cancel();S.score=Math.max(0,S.score-150);S.health=100;S.paused=false;S.last=performance.now();loadMission();}
function restartCampaign(){window.speechSynthesis?.cancel();S.mission=0;S.score=0;S.health=100;S.paused=false;S.last=performance.now();$('game-over').classList.add('hidden');openMap(true);}

let feedbackReturn='start-screen';
function openFeedback(returnTo='start-screen'){feedbackReturn=returnTo;stopAudio();$('feedback-status').textContent='';show('feedback-screen');}
function feedbackReport(){
 const data=new FormData($('feedback-form')),rating=data.get('rating'),message=$('feedback-message').value.trim();
 const heading=S.lang==='fr'?['Note','Catégorie','Commentaire']:['Rating','Category','Comment'];
 const lines=[`${heading[0]}: ${rating}/5`,`${heading[1]}: ${$('feedback-type').value}`,`${heading[2]}:`,message];
 if($('include-diagnostics').checked){let saved=null;try{saved=JSON.parse(storeGet('m23-save-v2'));}catch{}const details=S.lang==='fr'?'Informations techniques':'Diagnostics';lines.push('',`--- ${details} ---`,`Game: 0.3.0`,`Language: ${S.lang}`,`Mission: ${S.running?S.mission+1:(saved?.mission??-1)+1} / ${missions.length}`,`Score: ${S.running?S.score:saved?.score??0}`,`Screen: ${screen.width}x${screen.height} @ ${window.devicePixelRatio||1}x`,`Viewport: ${innerWidth}x${innerHeight}`,`Browser: ${navigator.userAgent}`);}
 return lines.join('\n');
}
function validateFeedback(){if(!$('feedback-form').reportValidity())return null;return feedbackReport();}
async function copyFeedback(){const report=validateFeedback();if(!report)return;const f=feedbackWords[S.lang];try{await navigator.clipboard.writeText(report);$('feedback-status').textContent=f.copied;}catch{$('feedback-message').focus();$('feedback-message').select();$('feedback-status').textContent=f.copyFailed;}}
function emailFeedback(e){e.preventDefault();const report=validateFeedback();if(!report)return;const f=feedbackWords[S.lang];location.href=`mailto:kamatekatende@gmail.com?subject=${encodeURIComponent(f.subject)}&body=${encodeURIComponent(report)}`;}

function update(dt){if(S.paused)return;S.time+=dt;S.cooldown-=dt;S.zoneWarn-=dt;let dx=S.touchX,dy=S.touchY;if(S.keys.has('left'))dx--;if(S.keys.has('right'))dx++;if(S.keys.has('up'))dy--;if(S.keys.has('down'))dy++;const mag=Math.hypot(dx,dy);if(mag>1){dx/=mag;dy/=mag;}if(dx||dy){S.player.faceX=dx;S.player.faceY=dy;}
 const oldX=S.player.x,oldY=S.player.y;S.player.x=Math.max(22,Math.min(938,S.player.x+dx*S.player.speed*dt));S.player.y=Math.max(26,Math.min(514,S.player.y+dy*S.player.speed*dt));
 const blocked=(missions[S.mission].zones||[]).find(([x,y,w,h,unlock])=>S.completed<unlock&&S.player.x+15>x&&S.player.x-15<x+w&&S.player.y+15>y&&S.player.y-15<y+h);if(blocked){S.player.x=oldX;S.player.y=oldY;if(S.zoneWarn<=0){toast(`${blocked[5]} • secure ${blocked[4]-S.completed} more objective${blocked[4]-S.completed===1?'':'s'}`);sfx('warning');S.zoneWarn=1.3;}}
 S.squad.forEach((s,i)=>{if(s.hp<=0)return;const angle=i%2?2.6:-2.6,target={x:S.player.x+Math.cos(angle)*(38+Math.floor(i/2)*24),y:S.player.y+Math.sin(angle)*(38+Math.floor(i/2)*20)};s.x+=(target.x-s.x)*Math.min(1,dt*4);s.y+=(target.y-s.y)*Math.min(1,dt*4);});
 S.enemies.forEach(e=>{if(e.hp<=0)return;e.x+=e.dir*e.speed*dt;if(Math.abs(e.x-e.home)>e.range)e.dir*=-1;e.shot-=dt;if(e.shot<=0&&dist(e,S.player)<350+S.mission*20){fire(e,S.player,'enemy');e.shot=Math.max(.62,1.18+Math.random()*1.05-S.mission*.18);}});
 S.bullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.side==='enemy'&&dist(b,S.player)<18){b.life=0;damagePlayer(14);burst(b.x,b.y,'#ca6a52',7);}if(b.side==='friendly'){const e=S.enemies.find(e=>e.hp>0&&dist(e,b)<18);if(e){e.hp--;b.life=0;burst(e.x,e.y,'#dcb16a',8);if(e.hp<=0){S.score+=100;feedback('+100');updateHud();toast('Hostile position neutralized');}}}});S.bullets=S.bullets.filter(b=>b.life>0);S.particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;});S.particles=S.particles.filter(p=>p.life>0);}

function soldier(x,y,uniform,name=false,down=false,angle=0){ctx.save();ctx.translate(x,y);if(down)ctx.rotate(1.25);ctx.fillStyle='#1a1f1c88';ctx.beginPath();ctx.ellipse(3,18,17,7,0,0,7);ctx.fill();ctx.fillStyle=uniform;ctx.fillRect(-10,-4,20,25);ctx.fillStyle='#6d5638';ctx.fillRect(-13,5,5,20);ctx.fillRect(8,5,5,20);ctx.fillStyle='#704a2e';ctx.beginPath();ctx.arc(0,-10,9,0,7);ctx.fill();ctx.fillStyle='#3b5035';ctx.fillRect(-9,-18,18,6);ctx.save();ctx.rotate(angle);ctx.fillStyle='#202923';ctx.fillRect(7,-2,25,5);ctx.fillStyle='#b78a55';ctx.fillRect(2,-3,10,7);ctx.restore();ctx.restore();if(name&&!down){ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillStyle='#101b1d';ctx.fillRect(x-42,y-39,84,18);ctx.fillStyle='#f4cf73';ctx.fillText('MAMADOU',x,y-26);}}
function draw(){const w=canvas.width,h=canvas.height;if(terrain.complete){ctx.globalAlpha=S.mission===0?.7:.82;ctx.drawImage(terrain,0,0,w,h);ctx.globalAlpha=1;}else{ctx.fillStyle='#294536';ctx.fillRect(0,0,w,h);}
 if(S.mission===0){ctx.fillStyle='#171a18aa';for(const [x,y,r] of [[90,80,70],[420,70,85],[760,460,105],[900,100,60]]){ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();ctx.strokeStyle='#a65338';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-r*.6,y);ctx.lineTo(x,y+12);ctx.lineTo(x+r*.55,y-8);ctx.stroke();}}
 if(S.mission===1){ctx.fillStyle='#15352599';for(let i=0;i<22;i++){const x=(i*151)%960,y=(i*97)%540;ctx.beginPath();ctx.arc(x,y,20+(i%3)*8,0,7);ctx.fill();}}
 if(S.mission===2){ctx.fillStyle='#102b2099';ctx.fillRect(0,0,w,175);ctx.fillRect(0,365,w,175);for(let x=20;x<w;x+=70){ctx.fillStyle='#1d462f';ctx.beginPath();ctx.arc(x,155+(x%3)*8,28,0,7);ctx.fill();ctx.beginPath();ctx.arc(x,380-(x%4)*7,31,0,7);ctx.fill();}}
 ctx.fillStyle=S.mission===2?'#665438dd':'#755f3dbb';ctx.beginPath();ctx.moveTo(0,238);ctx.bezierCurveTo(260,210,520,320,960,236);ctx.lineTo(960,310);ctx.bezierCurveTo(600,370,280,270,0,315);ctx.fill();
 (missions[S.mission].zones||[]).forEach(([x,y,zw,zh,unlock,label])=>{if(S.completed>=unlock)return;ctx.fillStyle='#9e342f38';ctx.fillRect(x,y,zw,zh);ctx.strokeStyle='#f06c59';ctx.lineWidth=3;ctx.setLineDash([10,8]);ctx.strokeRect(x+2,y+2,zw-4,zh-4);ctx.setLineDash([]);ctx.save();ctx.translate(x+zw/2,h/2);ctx.rotate(-Math.PI/2);ctx.fillStyle='#f5b0a4';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText(`RESTRICTED • ${label}`,0,4);ctx.restore();});
 ctx.fillStyle='#d7c28a';ctx.font='bold 13px system-ui';ctx.textAlign='left';ctx.fillText(missions[S.mission].place,20,28);
 S.targets.forEach(t=>{if(t.done)return;ctx.strokeStyle='#f1c664';ctx.lineWidth=3;ctx.beginPath();ctx.arc(t.x,t.y,27+Math.sin(S.time*5)*3,0,7);ctx.stroke();ctx.fillStyle=t.type==='civilian'?'#5e9a9c':t.type==='supplies'?'#aa8245':'#d3c8a4';if(t.type==='supplies')ctx.fillRect(t.x-15,t.y-13,30,26);else soldier(t.x,t.y,'#547d81');});
 S.enemies.forEach(e=>{if(e.hp>0)soldier(e.x,e.y,'#7d3e36',false,false,e.dir>0?0:Math.PI);else{ctx.globalAlpha=.45;soldier(e.x,e.y,'#7d3e36',false,true);ctx.globalAlpha=1;}});const facing=Math.atan2(S.player.faceY,S.player.faceX);S.squad.forEach(s=>soldier(s.x,s.y,'#375b7e',false,s.hp<=0,facing));soldier(S.player.x,S.player.y,'#244b82',true,S.health<=0,facing);
 S.bullets.forEach(b=>{ctx.fillStyle=b.side==='friendly'?'#ffe39a':b.side==='rocket'?'#ff844f':'#f36b54';ctx.beginPath();ctx.arc(b.x,b.y,b.side==='rocket'?8:4,0,7);ctx.fill();});S.particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,4,4);});ctx.globalAlpha=1;}
function loop(now){if(!S.running)return;const dt=Math.min(.033,(now-S.last)/1000||0);S.last=now;update(dt);draw();requestAnimationFrame(loop);}

const keyMap={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down'};
addEventListener('keydown',e=>{if((e.key==='p'||e.key==='P'||e.key==='Escape')&&S.running&&!S.paused){e.preventDefault();pauseGame();return;}if(keyMap[e.key]){e.preventDefault();S.keys.add(keyMap[e.key]);}if(e.code==='Space'||e.key==='Enter'){e.preventDefault();if(!$('dialogue').classList.contains('hidden'))$('continue-btn').click();else performAction();}});addEventListener('keyup',e=>keyMap[e.key]&&S.keys.delete(keyMap[e.key]));
document.querySelectorAll('[data-dir]').forEach(btn=>{const dir=btn.dataset.dir,down=e=>{e.preventDefault();S.keys.add(dir);btn.classList.add('pressed')},up=e=>{e.preventDefault();S.keys.delete(dir);btn.classList.remove('pressed')};btn.addEventListener('pointerdown',down);['pointerup','pointercancel','pointerleave'].forEach(x=>btn.addEventListener(x,up));});
const leftTouch=$('touch-zone-left'),rightTouch=$('touch-zone-right'),stick=$('virtual-stick'),knob=$('stick-knob');let stickOrigin={x:0,y:0};
function moveStick(e){if(e.pointerId!==S.touchPointer)return;const dx=e.clientX-stickOrigin.x,dy=e.clientY-stickOrigin.y,d=Math.hypot(dx,dy),limit=38,scale=d?Math.min(1,limit/d):0,px=dx*scale,py=dy*scale;knob.style.transform=`translate(${px}px,${py}px)`;S.touchX=Math.abs(dx)<5?0:dx/Math.max(limit,d);S.touchY=Math.abs(dy)<5?0:dy/Math.max(limit,d);}
leftTouch.addEventListener('pointerdown',e=>{if(S.paused||S.touchPointer!==null)return;e.preventDefault();S.touchPointer=e.pointerId;leftTouch.setPointerCapture(e.pointerId);const r=$('canvas-wrap').getBoundingClientRect();stickOrigin={x:e.clientX,y:e.clientY};stick.style.left=`${e.clientX-r.left}px`;stick.style.top=`${e.clientY-r.top}px`;stick.classList.remove('hidden');moveStick(e);});leftTouch.addEventListener('pointermove',moveStick);['pointerup','pointercancel','lostpointercapture'].forEach(type=>leftTouch.addEventListener(type,e=>{if(e.pointerId===S.touchPointer)resetTouch();}));
rightTouch.addEventListener('pointerdown',e=>{if(S.paused)return;e.preventDefault();navigator.vibrate?.(18);performAction();});
$('action-btn').addEventListener('pointerdown',e=>{e.preventDefault();navigator.vibrate?.(18);performAction();});$('map-btn').onclick=()=>openMap(false);$('start-btn').onclick=begin;$('how-btn').onclick=()=>show('how-screen');$('back-btn').onclick=()=>show('start-screen');$('restart-btn').onclick=()=>show('start-screen');
$('about-btn').onclick=()=>show('about-screen');$('about-back-btn').onclick=()=>show('start-screen');
$('feedback-btn').onclick=()=>openFeedback('start-screen');$('ending-feedback-btn').onclick=()=>openFeedback('ending-screen');$('feedback-back-btn').onclick=()=>show(feedbackReturn);$('feedback-form').addEventListener('submit',emailFeedback);$('copy-feedback-btn').onclick=copyFeedback;
$('retry-btn').onclick=retryMission;$('campaign-btn').onclick=restartCampaign;
$('pause-btn').onclick=pauseGame;$('resume-btn').onclick=resumeGame;$('save-btn').onclick=()=>saveGame(false);$('quit-btn').onclick=quitToMenu;$('continue-save-btn').onclick=loadSavedGame;
$('language-select').addEventListener('change',e=>{S.lang=e.target.value;storeSet('m23-language',S.lang);applyLanguage();applyFeedbackLanguage();});
$('settings-btn').onclick=()=>{S.paused=true;silenceAll();$('settings-dialog').showModal();};$('settings-dialog').addEventListener('close',()=>{if(S.running){const blocked=!$('dialogue').classList.contains('hidden')||!$('pause-overlay').classList.contains('hidden')||!$('game-screen').classList.contains('active');S.paused=blocked;S.last=performance.now();if(!blocked)activateAudio();}});
[['music-volume','music','music-value'],['gun-volume','gun','gun-value'],['effects-volume','fx','effects-value']].forEach(([id,key,out])=>{$(id).addEventListener('input',e=>{audio[key]=+e.target.value/100;$(out).value=e.target.value+'%';storeSet('m23-'+key,e.target.value);});const saved=storeGet('m23-'+key);if(saved!==null){$(id).value=saved;$(out).value=saved+'%';audio[key]=+saved/100;}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&S.running&&!S.paused)pauseGame();});
let deferredInstallPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('install-btn').classList.remove('hidden');});
$('install-btn').onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;}else $('install-dialog').showModal();};
if(window.matchMedia('(display-mode: standalone)').matches||navigator.standalone==true)$('install-btn').classList.add('hidden');
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
applyLanguage();applyFeedbackLanguage();updateSaveButton();
